### ISSUE TITLE
iron-flex-layout demo freezing in firefox

### ISSUE THREAD

**Issue by lingtalfi** [PolymerElements/iron-flex-layout#102]
### Description

The demo for iron-flex-layout makes firefox crash (unusable to be more precise).

https://elements.polymer-project.org/elements/iron-flex-layout?view=demo:demo/index.html&active=iron-flex-layout
### Expected outcome

go to the page: https://elements.polymer-project.org/elements/iron-flex-layout?view=demo:demo/index.html&active=iron-flex-layout 
with firefox and see a demo.
### Actual outcome

The page seems to perform a very heavy computation that never ends.
The only way out is to force quit Firefox, even then, after restarting, Firefox is still slow every time when a iron-flex-layout page is approached in the polymer elements section (https://elements.polymer-project.org/elements)
### Steps to reproduce
1. Open the above url in Firefox
### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I can't reproduce this in the latest Firefox :(
