### ISSUE TITLE
How to get rid of the deprecated file warning in the console?

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/iron-flex-layout#108]
[Please answer this question on SO](http://stackoverflow.com/q/41952346/1640892).

**Comment by notwaldorf** [comment]
One of your elements, or more likely, a dependency of them imports either `paper-styles/paper-styles.html`, or `iron-flex-layout/classes/iron-flex-layout`. Can't really figure out anything more than that without looking at your `bower.json` or what your dependency tree looks like
