### ISSUE TITLE
Failing lint

### ISSUE THREAD

**Issue by adam-azarchs-10x** [PolymerElements/iron-flex-layout#116]
### Description
It appears that the example added in #112 caused projects which depend on `iron-flex-layout` to start failing eslint.  It doesn't seem to like nested html comments.

### Expected outcome

Lint passes.

### Actual outcome

```bash
$ polymer lint
warn:    /bower_components/iron-flex-layout/iron-flex-layout.html:56:81
    <iron-flex-layout> is undefined.
warn:    /bower_components/iron-flex-layout/iron-flex-layout.html:56:81
    <iron-flex-layout> is undefined.
```

### Steps to reproduce

1. Create a project that depends transitively on iron-flex-layout (pretty much any project).
2. Run `polymer lint`

**Comment by notwaldorf** [comment]
On it :(

**Comment by notwaldorf** [comment]
@adam-azarchs-10x ive tagged a new release. Please let me know if you still see this error (I thiiiiink it should be fine?)

**Comment by Peppe** [comment]
Could you pull this change to the 2.0-preview branch? The uncommented code is evaluated by IE11 and gives a completely blank page on the latest version.
