### ISSUE TITLE
Chrome 65 could break some Polymer 1.x and 2.x websites

### ISSUE THREAD

**Issue by chosh31** [PolymerElements/iron-flex-layout#132]
In Link: https://www.polymer-project.org/blog/2017-10-18-upcoming-changes

 What you should do in the next month or two:

 - [x] Ensure that you're running the latest 1.x or 2.x release (1.10.1 or newer for 1.x; 2.1.1 or newer for 2.x).
 - [ ] If you have any HTML imports that contain ordinary style tags—not wrapped in a custom-style element or inside a template—use a custom-style element instead, to ensure the styles are moved into the main document.

Did you have a second phase patch?
- In source: https://github.com/PolymerElements/iron-flex-layout/blob/1.x/iron-flex-layout.html#L62

**Comment by kobleistvan** [comment]
Seems that even if the <style> tags are wrapped in <custom-style> tags, Chrome still gives warning in console regarding deprecation. Should it be ONLY <custom-style>, without <style> tags inside of them? Thanks
