### ISSUE TITLE
Guide is missing code

### ISSUE THREAD

**Issue by ssundarraj** [PolymerElements/iron-flex-layout#134]
Code samples on https://elements.polymer-project.org/guides/flex-layout are blank.
![flex-missingdocs](https://user-images.githubusercontent.com/4509724/34689486-8a2a5d8c-f46a-11e7-9666-877673a01406.png)

**Comment by notwaldorf** [comment]
hmm, looks fine here (tried Chrome and FF):
<img width="882" alt="screen shot 2018-01-08 at 12 19 35 pm" src="https://user-images.githubusercontent.com/1369170/34690481-36102d86-f46e-11e7-8748-6f22eecd6876.png">

What browser? Any more details?

**Comment by ssundarraj** [comment]
I am on Chrome 63.0.3239.108. I tried again and it worked. That's weird. I'll reopen if I'm able to repro.
