### ISSUE TITLE
insert hidden globally - breaks UI, hidden style is not applied even on modern browsers

### ISSUE THREAD

**Issue by tavisca-dpingale** [PolymerElements/iron-flex-layout#140]
1. Till now we were using iron-flex-layout (#^1.3.7) in old project and in new project (#^2.0.1)
2. But suddenly the UI started breaking, issues getting reported in projects
3. We started debugging a lot
4. The elements which we want to be hidden seems to getting visible on page
5. At end we found that the hidden attribute styling is not getting applied.
6. The reason for this we found the issue with updated version having new script for hidden.
7. We downgraded the version in our bower and things work fine...
8. This also breaks the UI on version 2.0.2 having the same script in it

### Browsers Affected (we tested)

- [x] Chrome
- [x] Firefox

**Comment by notwaldorf** [comment]
Did this work in 2.0.0 or any 2.x version of this element?

/cc @e111077 @valdrinkoshi @kevinpschaaf

**Comment by notwaldorf** [comment]
Also, could you post a code snippet of where you’re using hidden and it doesn’t work? Is it in the main document, in an element, etc

**Comment by tavisca-dpingale** [comment]
It was working till iron-flex-layout (#^1.3.7) and  (#^2.0.1). I have used it in a component made for a project. 

After you updated iron-flex-layout (#^1.3.8) and  (#^2.0.2) the issue seen is below.
Here is the screenshot of the browser where you can clearly see the hidden elements are visible the styling is not loaded.

![group](https://user-images.githubusercontent.com/15605278/36245568-c00851fc-1251-11e8-8cbd-bc674e39663b.png)

**Comment by notwaldorf** [comment]
Is this a Polymer 2 app with hybrid elements, then? Like, is `<tlg-report>` a hybrid element, or a pure 2.0 element? Can you show the `<tlg-report>` snippet and how it's importing `iron-flex-layout` so that I can try to write some reproducible code? (Or better yet if you have one already)

(we ran this change against many apps using Polymer and it was all good, so I think you're maybe hitting an edge case)

As a side note, if you just want the workaround, in `tlg-report` you can just add this style directly, and it should fix it:
```
[hidden] {
   display: none !important;
}
```

**Comment by tavisca-dpingale** [comment]
I am using it as below in polymer 1.0 project

<link rel="import" href="../../bower_components/polymer/polymer.html" />
<link rel="import" href="../../bower_components/vaadin-grid/vaadin-grid.html" />
<link rel="import" href="../../bower_components/paper-toast/paper-toast.html" />
<link rel="import" href="../../bower_components/iron-flex-layout/iron-flex-layout.html" />
<link rel="import" href="../../bower_components/iron-flex-layout/iron-flex-layout-classes.html" />
<link rel="import" href="../../bower_components/paper-tooltip/paper-tooltip.html">
<link rel="import" href="../../bower_components/iron-fit-behavior/iron-fit-behavior.html">

<dom-module id="lg-report">
    <template>
        <style include="iron-flex">
             :host { }
</style>

<div class="searchContainer" hidden$="[[!enableSearch]]">
     The text to hide
</div>

</template>
</dom-module>
<script>
    Polymer({
        is: 'lg-report',
        properties: {
             enableSearch: {
                type: Boolean,
                value: false
            }
     }
})
</script>

I was known about the workaround, but the hidden style was not applied after introduction of new script that what I found after debugging.

**Comment by paresy** [comment]
I can verify this issue. We have a plain Polymer 1.x app, that showed elements which should be hidden. As already pointed out the [hidden] style is missing/not being applied. 
![image](https://user-images.githubusercontent.com/260376/36314420-18a01ec4-1335-11e8-8638-f14039b0e291.png)

**Comment by nochev** [comment]
Hello,
Is this fix https://github.com/PolymerElements/iron-flex-layout/commit/f5a62ee975ef755d6fe47ccd9682b6a691e5c352 will be released in 1.x version ?

**Comment by notwaldorf** [comment]
I just released the fix @nochev mentioned as 1.3.9. @tavisca-dpingale @paresy Let me know if updating to this version fixes your project 🙏

**Comment by nochev** [comment]
@notwaldorf update is fixing our project. Thanks.

**Comment by paresy** [comment]
@notwaldorf  Works! Thanks.

**Comment by notwaldorf** [comment]
Yay! Sorry about that!
