### ISSUE TITLE
Behavior doesn't match the migration notes (CSS @apply)

### ISSUE THREAD

**Issue by Manyuuz** [PolymerElements/iron-flex-layout#15]
Hi !

I'm currently working on my personal website using Polymer 1.0. Therefore, I had to migrate from its previous version, and I found out that the behavior of "iron-flex-layout", or more precisely the styling with mixins it provides, does not match the migration notes. Indeed, notes are suggesting that you can @apply(...) several mixins at the same time (c.f. screenshot), but it doesn't seem to work, as described in an issue from the 0.9.1 here : https://github.com/Polymer/polymer/issues/1601.

I guess that the "Layout" part of migration notes should be updated to match how it should be used as it can be very misleading (and also, the < link rel="import" > tag corresponds to a previous version of the layout component should be updated).

Thanks :)

![capture d ecran 2015-05-30 a 04 03 41](https://cloud.githubusercontent.com/assets/3438543/7895379/00d24bf0-0681-11e5-9fbb-f54f0ac2c65a.png)

**Comment by Shrugs** [comment]
Can confirm that the behavior has changed. This worked as advertised in 0.9.0, but seems to fail on ^1.0.0.

**Comment by batista** [comment]
@Shrugs with the merge of Polymer/docs#1173 this should be closed
