### ISSUE TITLE
Docs missing from catalog

### ISSUE THREAD

**Issue by basarat** [PolymerElements/iron-flex-layout#16]
Not visible here : https://elements.polymer-project.org/elements/iron-flex-layout

Also on the migration page (https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes) link to the `demo` doesn't work : 
![image](https://cloud.githubusercontent.com/assets/874898/8002747/a8562954-0bb4-11e5-9455-c875afb6c1ce.png)

**Comment by arthurevans** [comment]
Docs don't show up. Demo shows up if you're looking at another iron- element demo, but not if you select the docs page for iron-flex-layout.

https://elements.polymer-project.org/elements/iron-flex-layout?view=demo:demo/index.html

**Comment by adammarton** [comment]
+1

**Comment by pensierinmusica** [comment]
+1

**Comment by klarkc** [comment]
+1

**Comment by tpluscode** [comment]
+1

**Comment by antono** [comment]
:-1:

**Comment by WesleyBatista** [comment]
+1

**Comment by TrentBrown** [comment]
+1
