### ISSUE TITLE
Need to doc this element to show how to use these idiomatically

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-flex-layout#17]
We need to provide better explanation of how to use these layout styles.

For example, show how developers can do something like:
http://jsbin.com/zofidu/edit?html,output

**Comment by arthurevans** [comment]
... But first they have to exist. @sjmiles are you planning on checking in the `classes.html` shown here? Or are we waiting for something other changes to the styling system first (like: https://github.com/Polymer/polymer/issues/1876)?
