### ISSUE TITLE
Equivalent for auto-vertical attribute?

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-flex-layout#18]
Are we going to add an equivalent of the 0.5 auto-vertical attribute? I don't know whether it's important or not -- I just noticed in trying to update the docs that there appeared to be no equivalent in iron-flex-layout.

**Comment by addyosmani** [comment]
I can't recall using `auto-vertical`, however here's a quick GitHub search on [usage](https://github.com/search?l=html&q=%22polymer%22+%22auto-vertical%22&ref=searchresults&type=Code&utf8=%E2%9C%93).

**Comment by notwaldorf** [comment]
@athur What did `auto-vertical` do, do you recall? (I've never seen it in action)

**Comment by notwaldorf** [comment]
@arthurevans @addyosmani Should we close this? I don't really know what the attribute does (it's not canon for flexbox) and there haven't been any requests from the community to resuscitate it

**Comment by notwaldorf** [comment]
Closing. Please re-open and ping me if anyone really needs it and remembers explicitly what this did :)
