### ISSUE TITLE
Should I use direct classes or mixins?

### ISSUE THREAD

**Issue by eaflores4** [PolymerElements/iron-flex-layout#20]
Hello I pretty new to Polymer and I was noticing that I could directly apply a iron-flex-layout class to an element, such as class="flex". The migration guide does not show this behavior it only shows that I can include these classes as a mixins. I also noticed that these iron-flex-layout classes that can be directly applied to an element come from a file in the iron-flex-layout folder, iron-flex-layout/classes/iron-flex-layout.html. How is this file being included in my project since I am not including it? Also, what should I use, mixins, direct styling, or both? Thanks.

**Comment by pensierinmusica** [comment]
+1

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1246
