### ISSUE TITLE
`--layout-fixed-top` does not have the effect of `postion: fixed` 

### ISSUE THREAD

**Issue by butterandfly** [PolymerElements/iron-flex-layout#21]
It seems that the code below is not working:
```
    --layout-fixed-bottom:,
    --layout-fixed-left:,
    --layout-fixed-right:,
    --layout-fixed-top: {
      position: fixed;
    };
```

**Comment by morethanreal** [comment]
https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout.html#L280

That syntax doesn't look correct to me. @notwaldorf can you take a look?
