### ISSUE TITLE
Documentation does not exist.

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/iron-flex-layout#27]
Where is the documentation for this element?

**Comment by SmokyBob** [comment]
https://elements.polymer-project.org/guides/flex-layout

**Comment by grokys** [comment]
It would be nice to display these docs from the catalog page instead of displaying "no documentation found"

**Comment by garlicnation** [comment]
Fixed locally. Will appear in the catalog on the next push.

<img width="1436" alt="screen shot 2015-09-29 at 9 33 09 am" src="https://cloud.githubusercontent.com/assets/1105965/10171122/4bfba272-668d-11e5-8984-c407bd00a7b8.png">

**Comment by samccone** [comment]
zomg :sparkles: :heart:

**Comment by garlicnation** [comment]
https://elements.polymer-project.org/elements/iron-flex-layout
