### ISSUE TITLE
Self-stretch doesn't apply on paper-card when inside a layout horizontal

### ISSUE THREAD

**Issue by isorna** [PolymerElements/iron-flex-layout#29]
I've been following the flex-layout guide and it says that you can use `class="flex self-stretch"` on a tag inside a tag with `class="layout horizontal"`, so that all boxes use the same height.

Using a `<paper-card>` element, seems that the shadow doesn't apply correctly this behaviour, or I'm not smart enough to get it work without applying `class="layout horizontal"` again to my `<paper-card>`'s elements.

![screenshot 2015-08-25 at 13 33 00](https://cloud.githubusercontent.com/assets/39324/9465580/19b551f2-4b2e-11e5-9bdb-c5448b8699b0.png)
![screenshot 2015-08-25 at 13 34 29](https://cloud.githubusercontent.com/assets/39324/9465587/239cb390-4b2e-11e5-82fb-8b1d3569d563.png)

Maybe this issue should be submitted to https://github.com/PolymerElements/paper-card ?

Polymer rocks anyway!

**Comment by notwaldorf** [comment]
This should have already been fixed. `paper-card` no longer uses a `paper-material` custom element, just its style.

**Comment by isorna** [comment]
Thanks Monica!
