### ISSUE TITLE
:root selector causing side effects

### ISSUE THREAD

**Issue by petermikitsh** [PolymerElements/iron-flex-layout#31]
From [iron-flex-layout.html#L21](https://github.com/PolymerElements/iron-flex-layout/blob/6f67f2ea4aba5c0171392477bd2956c8b781bb25/iron-flex-layout.html#L21):

```html
<style is="custom-style">
  :root {
    --layout: {
       display: -ms-flexbox;
       display: -webkit-flex;
       display: flex;
    };
   ...
  }
</style>
```

This seems to force a flex layout on the `body` element, throwing off the entire viewport's layout.

Css style applied:

<img width="325" alt="screen shot 2015-09-21 at 3 26 23 pm" src="https://cloud.githubusercontent.com/assets/1571918/10006844/9519fc74-6075-11e5-9241-6c66f3e3a246.png">

How the viewport renders:

<img width="1435" alt="layout" src="https://cloud.githubusercontent.com/assets/1571918/10006850/9e898158-6075-11e5-92ba-6747b38ddc00.png">

I'm also using ng-boilerplate and this issue is only evident post build.

**Comment by notwaldorf** [comment]
That line in `iron-flex-layout` just defines the mixin, it doesn't apply it to anything. Could you create a jsbin with your repro steps, or post your code? It's kind of hard to tell what's going on without looking at any code :)

**Comment by notwaldorf** [comment]
Closing this, since there's no answer and no repro steps :(
