### ISSUE TITLE
Fullbleed creates an extra scroller

### ISSUE THREAD

**Issue by emersonbottero** [PolymerElements/iron-flex-layout#33]
On windows + chrome an extra scroller is displayed #396. It was fix somehow but now is back again.

**Comment by notwaldorf** [comment]
Can you reproduce this in a JSBin, or post a snippet of your code? I think what's inside your app matters, since `fullbleed` by itself works seems to work fine: http://jsbin.com/mohiwu/edit?html,output

**Comment by emersonbottero** [comment]
Any page from Polymer shows the error for me

in the link you send works fine when is not in live preview
![image](https://cloud.githubusercontent.com/assets/12377432/10985728/cbe2ab80-840a-11e5-8d55-532da1a00319.png)

if you click in live preview the error occurs
![image](https://cloud.githubusercontent.com/assets/12377432/10985743/ffb29f06-840a-11e5-9ab1-d569f77cca1d.png)

**Comment by emersonbottero** [comment]
@notwaldorf don't know if you saw the link  #396 but it only happens on windows + Chrome

**Comment by bdore** [comment]
It's caused by height:100vh property in iron-flex-layout.html

**Comment by notwaldorf** [comment]
I don't know what the link #396 refers to (there's no issue on this repo with that id), but there was a typo in the original jsbin (the classes were actually meaningless). Here is a screenshot from chrome on windows, where i still can't repro this :(

![Uploading Screen Shot 2015-12-15 at 4.56.30 PM.png…]()
