### ISSUE TITLE
Do layout classes now need to be imported explicitly?

### ISSUE THREAD

**Issue by czellweg** [PolymerElements/iron-flex-layout#36]
I've updated a Polymer element of mine when I've noticed the layouting did not seem to work anymore. After some digging, I've seen that I can import `iron-flex-layout/classes/iron-flex-layout` if I want to continue using the layout properties directly in the markup (as opposed to mix-ins).

It appears that using the above mentioned import, the `/deep/`combinator is again used (which will be deprecated, or already is?) which will layout the elements like before.

So my question:
 - can we use the layout properties directly in markup *without* the need to import `iron-flex-layout/classes/iron-flex-layout`?

I've added a short example to illustrate the case (*you will have to change the imports paths!*):

    <html lang="">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Testing flex layouting</title>
        <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
        
        
        <link rel="import" href="../../polymer/polymer.html">
        <link rel="import" href="../../iron-flex-layout/iron-flex-layout.html">
        <link rel="import" href="../../iron-flex-layout/classes/iron-flex-layout.html">
        
      </head>

    <dom-module id="flex-test">

      <style>
        .container {
          @apply(--layout-horizontal);
          @apply(--layout-wrap);
          background-color: gray;
        }

        .old {
          margin-top: 5px;
          background-color: gray;
        }

        .container div, .layout div {
          background-color: lightgray;
          padding: 5px;
          margin: 5px;
          width: 300px;
        }
      </style>

      <template>
        <div>Example using mixins</div>
        <div class="container">
          <div>One</div>
          <div>Two</div>
          <div>Three</div>
        </div>

        <div>Example using layout properties directly in markup</div>
        <div class="old layout horizontal">
          <div>One</div>
          <div>Two</div>
          <div>Three</div>
        </div>
      </template>

      <script>
        Polymer({ is: 'flex-test' });
      </script>

    </dom-module>

      <body unresolved full>
        <flex-test></flex-test>
      </body>
    </html>

**Comment by notwaldorf** [comment]
If you just want to use the layout mixins (not the classes), you need to just import `iron-flex-layout/iron-flex-layout.html`. I think the problem in your example is actually the `--layout-wrap` mixin you're applying (which forces the horizontal layout to wrap around). Note that the same happens if you change your classes example to `<div class="old layout horizontal wrap">`

Here's a jsbin with your example that you can play around with: http://jsbin.com/sacazi/edit?html,output

Does this answer your question?

**Comment by czellweg** [comment]
Great, thank you @notwaldorf!
