### ISSUE TITLE
/deep/ alternative

### ISSUE THREAD

**Issue by oathcomrade** [PolymerElements/iron-flex-layout#37]
Browser returns the folowing warning:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by cdata** [comment]
Thanks for reporting. We are currently working on changes to minimize the impact from `/deep/` being removed. Please track https://github.com/PolymerElements/iron-flex-layout/pull/32 for the latest on this.

**Comment by notwaldorf** [comment]
For now, we recommend using the mixin version of the flex layout classes. If you don't have a selector available, you can always make one for the one class you need, like:
```css
.fit {
  @apply(--layout-fit);
}
```

**Comment by notwaldorf** [comment]
Going to merge this into https://github.com/PolymerElements/iron-flex-layout/issues/23, since that's the issue that's tracking the generic "What do we do about `/deep/`" problem.
