### ISSUE TITLE
"align-items: stretch" missing from variables.

### ISSUE THREAD

**Issue by ReeceGoddard** [PolymerElements/iron-flex-layout#48]
There is --layout-start, --layout-center, and --layout-end. But no --layout-stretch.

Is there a reason for this being missing, or just a bug?

**Comment by notwaldorf** [comment]
`stretch` is the default, so it's essentially the same as just saying `@apply(--layout-horizontal);`, with no other properties. If you want to send a PR to add it though, that would be awesome!

**Comment by ReeceGoddard** [comment]
I tried submitting a PR but I don't have permission.

**Comment by notwaldorf** [comment]
You can't clone and just make a commit to this repo; you need to fork it and send a PR. Here is the github workflow for that: https://help.github.com/articles/using-pull-requests/

**Comment by ReeceGoddard** [comment]
Okay, thanks for the info.

**Comment by notwaldorf** [comment]
Closing this, since it's not really bug -- the functionality is already there
