### ISSUE TITLE
`<style>` outside of `<template>` - is there a reason?

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-flex-layout#53]
https://github.com/PolymerElements/iron-flex-layout/blob/master/demo/demo-snippet.html#L36

Is this for a specific reason?
I'm working on porting the demos to Dart and run into an issue that the template in `attached()` is empty.
I don't think it's related, I just try to understand the demo code better.

**Comment by notwaldorf** [comment]
Nope, that's my bad!
