### ISSUE TITLE
style classes vs mixins  > rendering differences

### ISSUE THREAD

**Issue by manfield** [PolymerElements/iron-flex-layout#59]
Due to the "/deep" deprecation, we're refactoring the whole application, substituting classes to mixins.
It seems we have some issues on flex applied to vertical layout.

This is the block, before refactoring:
<img width="403" alt="2015-11-27_1055" src="https://cloud.githubusercontent.com/assets/397671/11438556/e32f4a7c-94f5-11e5-9c9b-9fe3f88f9b0d.png">

Let's consider the block labeled "Firma"

```
<!--FIRMA -->
            <div class="vertical layout cell" 
            on-tap="onToggleFirmaPrincipale"
            >
                <div class="title">Firma</div>
                <div class="horizontal layout flex">
                    <div style="pointer-events: none;" class="self-center">
                        <paper-checkbox
                            disabled='[[_static("App.Firma.IsEnabled",value,classe)]]' 
                            checked="[[_isSignedPrincipale(value._rnd)]]"
                        ></paper-checkbox>
                    </div>
                </div>
            </div>
<!--//FIRMA -->
```

This is how it appears after:
<img width="390" alt="2015-11-27_1054" src="https://cloud.githubusercontent.com/assets/397671/11438583/1af1e8b6-94f6-11e5-8885-948596c57b6d.png">

```
<!--FIRMA-->
            <div class="mgs-vertical cell" 
            on-tap="onToggleFirmaPrincipale"
            >
                <div class="title">Firma</div>
                <div class="mgs-flex mgs-horizontal">
                    <!--  PREVENT TOOGLE EVENT -->
                    <div style="pointer-events: none;" class="mgs-self-center">
                        <paper-checkbox
                            disabled='[[_static("App.Firma.IsEnabled",value,classe)]]' 
                            checked="[[_isSignedPrincipale(value._rnd)]]"
                        ></paper-checkbox>
                    </div>
                </div>
            </div>
<!--//FIRMA-->
```

where

```
			.mgs-flex{
			    @apply(--layout-flex);
			}
			.mgs-horizontal{
				@apply(--layout-horizontal);
			}
			.mgs-vertical{
				@apply(--layout-vertical);
			}
			.mgs-self-center{
				@apply(--layout-self-center);
			}

```

It seems that flex inside a vertical layout stretches completely the element to the full height, going over other sibling divs.

Other stuff works as expected (except horizontal and vertical reverse, we opened an issue yesterday).

**Comment by notwaldorf** [comment]
Is there a chance you could repro this in a jsbin, please? Here's a sample one to get you started: http://jsbin.com/cagaye/edit?html,output

**Comment by manfield** [comment]
Hello,
I reproduced here:
http://jsbin.com/jotejosepo/edit?html,output

Try to give a look.
Thanks a lot.

**Comment by notwaldorf** [comment]
Eeek, sorry for dropping the ball on this issue. I'll take a look tomorrow!

**Comment by manfield** [comment]
toc toc :)

**Comment by notwaldorf** [comment]
The bug seems to be coming from the `--layout-flex` application on the inner horizontal container (that holds the header and the checkbox). After removing that, it's fine: http://jsbin.com/pewala/edit?html,output

The classes and mixins versions for the flex-basis of `.flex` and `--layout-flex` are completely different, but I don't know why that's the case.

@keanulee @frankiefu Any idea why this is?

**Comment by keanulee** [comment]
@notwaldorf What exactly is the issue? I opened the two jsbin links above, and I don't see any overlapping divs (i.e. header and content are adjacent, not overlapping).

**Comment by manfield** [comment]
This is the issue:
<img width="327" alt="issue_1" src="https://cloud.githubusercontent.com/assets/397671/12671692/b881326a-c671-11e5-8f5b-087c2f255825.png">

You may see the same in the very first comment of this thread:

<img width="386" alt="first_comment" src="https://cloud.githubusercontent.com/assets/397671/12671712/d626a782-c671-11e5-9387-61d9a4799787.png">

**Comment by notwaldorf** [comment]
I don't think I can reproduce this anymore. Here's the same jsbin, updated: http://jsbin.com/pewala/edit?html,output

The mixin and classes version look the same, with the same DOM:
<img width="515" alt="screen shot 2016-02-16 at 3 46 44 pm" src="https://cloud.githubusercontent.com/assets/1369170/13095157/7f64bba8-d4c4-11e5-99b8-acabfeef0f3d.png">

Please let us know if this is still an issue for you.

**Comment by manfield** [comment]
Hi, yes I tried yesterday after a framework update. The issue seems to be solved by latest releases.
Thanks a lot for your support.
