### ISSUE TITLE
Feature request: self alignment along main axis

### ISSUE THREAD

**Issue by masaoliou** [PolymerElements/iron-flex-layout#64]
I would like to align the first two `<li>`  to the left and the third `<li>` to the right like this:

```html
<ul class="layout horizontal start-justified">
  <li>one</li>
  <li>two</li>
  <li class="self-end">three</li>
</ul>
```
Note that `class="self-end"` applied to the third `<li>` doesn't do the job because according to [the guide](https://elements.polymer-project.org/guides/flex-layout), it aligns the third `<li>` to the bottom of its container.

**Comment by notwaldorf** [comment]
@masaoliou do you have an example of how this would be done with plain flexbox code?

**Comment by notwaldorf** [comment]
Here's an example: http://jsbin.com/doqozit/edit?html,output.

Closing, since I don't think there's a flex property that can do what you want.

**Comment by masaoliou** [comment]
Your insightful example already shows me the ingenious approach that fully satisfies my requirement and makes this request invalid.

Thank you very much for the help!

**Comment by notwaldorf** [comment]
No worries, glad it worked out!
