### ISSUE TITLE
Missing classes/mixins related to align-items and align-content

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/iron-flex-layout#67]
Using massively flex layout in one of my project, I discovered some missing classes/mixins related to flex.
Concerning the alignment in cross axis, the following are missing:
```
    --layout-stretch: {
      align-items: stretch;
    };
```
and
```
    --layout-baseline: {
      align-items: baseline;
    };
```
Concerning, multi-lines, all classes / mixins related to `align-content` are missing.

**Comment by notwaldorf** [comment]
`align-items: stretch` is the default, which is what it's not included. `baseline` is indeed missing.

**Comment by notwaldorf** [comment]
@MeTaNoV If you were to put together a PR adding these missing attributes, I would absolutely merge it, by the way :)

**Comment by MeTaNoV** [comment]
oh, OK, if I got green light now! :)

**Comment by MeTaNoV** [comment]
@notwaldorf KTAL!
