### ISSUE TITLE
Layout vertical/horizontal broken on canary

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-flex-layout#71]
`--layout-vertical, --layout-vertical-reverse` should have `min-height: 0`,
`--layout-horizontal, --layout-horizontal-reverse` should have `min-width: 0`
http://stackoverflow.com/questions/29907626/flexbox-max-height-interpretation-change-on-chrome#answer-29909047

Without those, the rendering on chrome canary and firefox breaks.

**Comment by notwaldorf** [comment]
@valdrinkoshi Do you mean `--layout-flex-vertical`? `iron-flex-vertical` doesn't exist :)

**Comment by valdrinkoshi** [comment]
Lol my bad, updating the description

**Comment by bsinc** [comment]
Definitely looking for an update for this! My whole web-app relies on iron-flex-layout, I just updated to Chrome 48 and it's broken. Having to put the min-width and min-height fix in manually is becoming a huge pain.

**Comment by ebidel** [comment]
Chrome 48 changes are causing issues: https://twitter.com/sunshinex0_/status/692434593262243842

**Comment by notwaldorf** [comment]
@valdrinkoshi would you mind sending a PR for this, please? :)

**Comment by valdrinkoshi** [comment]
sure, i'll assign this to myself and add it to my TODO list ;)

**Comment by notwaldorf** [comment]
Thanks so much! Here's some internet cake! 🍰🍰🍰

**Comment by bsinc** [comment]
looks like chrome pushed an update last night to fix this issue! 
https://code.google.com/p/chromium/issues/detail?id=580196

The version of chrome that caused the problem for me was: 48.0.2564.82
Now updated to: 48.0.2564.97

Everything is working great! :)

**Comment by bsinc** [comment]
Actually... I spoke too soon.

I'm having this problem:
https://jsfiddle.net/L341am4o/1/

The second section with class "fix" has the min-width: 0; "hack" to fix it.

**Comment by valdrinkoshi** [comment]
Adding `min-width: 0; min-height: 0` would be a breaking change for certain css selectors: in this example you can see how the `min-width` gets overridden if the css is defined before the fix http://jsbin.com/viqeru/9/edit?html,output
In more complex cases this style might be set through custom styles/mixins. The risk of overriding the `min-width/height` is high,

This issue happens on chrome & firefox, but not on safari. I would wait for browsers to fix this, or ask the Polymer user to handle this in their app until this gets fixed.

cc/ @ebidel @notwaldorf, LMKWYT

**Comment by notwaldorf** [comment]
Yeah, I agree with @valdrinkoshi. I think us fixing this will open up a jar of spiders :(

**Comment by notwaldorf** [comment]
@valdrinkoshi @ebidel what do you think about closing this issue? It seems to be a browser bug, and as Valdrin explained in the previous comment, us fixing this is a potential giant breaking change

**Comment by valdrinkoshi** [comment]
Yeah, we should close this. 
Hopefully this issue will be easy enough to find for people that face this issue. The solution is to set `min-height` or `min-width` to the flex elements.
