### ISSUE TITLE
iron-flex-layout demo not working

### ISSUE THREAD

**Issue by rkommine** [PolymerElements/iron-flex-layout#77]
Hi,

I have started learning polymer. To start with my learning project first I tries to create a simple webpage with iron-flex-layout.

So I have used the below code as per the the information given in using elements.

`<!DOCTYPE html>`
`<html>`
`<head>`
	`<title>testing</title>`
	`<script src="lib/polymer/webcomponentsjs/webcomponents-lite.min.js"></script>`
	`<link rel="import" href="lib/polymer-elements/iron-flex-layout/iron-flex-layout.html">`
	`<style is="custom-style">`
          `.flex {`
            `@apply(--layout-horizontal);`
          `}`
        `</style>`
`</head>`
	`<body>`
    	

        `<div class="container flex">
          <div>one</div>
          <div>two</div>
          <div>three</div>
        </div>
	</body>`
`</html>`

But when I open the browser the I am not able to see the layout as expected. It is just printing the following:

one
two
three

Not

one two three

Could you please help.

Regards,
Ramakrishna

**Comment by notwaldorf** [comment]
Are you sure you're importing `iron-flex-layout` correctly? Make sure that you ran `bower install` correctly, and that there are no errors on your page. Here's a super basic jsbin with your code, showing that it works fine: http://jsbin.com/visibif/edit?html,output

Closing, as I think there's a problem with your setup, not with the element.
