### ISSUE TITLE
[Documentation] Flex layout guide deprecation

### ISSUE THREAD

**Issue by grebett** [PolymerElements/iron-flex-layout#78]
Hello Polymer team! Thank you for your great job and very clear documentation around here.

Reading the [flex-layout guide](https://elements.polymer-project.org/guides/flex-layout), I have noticed that, even though it speaks about the soon-to-be deprecation, there are no mention of the new `iron-flex-layout.html` and `iron-flex-layout-classes.html`.

The documentation and demo within the repository are quite explicit about how to use these new elements, but users may look first at the deprecated documentation, leading them to erroneous usage.

I'd like to submit you a pull request (a minima a reference to the file inline documentation) but I haven't found the guide repository.

Thank you for reading,

grebett

**Comment by notwaldorf** [comment]
There's already a PR in flight for that: https://github.com/Polymer/polymer-element-catalog/pull/248.

FWIW, the guide already talks about the `iron-flex-layout` mixins, it just hasn't been updated for the new classes approach, which literally got merged last week 😊
