### ISSUE TITLE
Selector with multiple custom props is not applied

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-flex-layout#8]
From the mailing list (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/polymer-dev/ee0FIc_uiCg/iPPkGqFYRPsJ) 

     --layout-fixed-bottom:,
        --layout-fixed-left:,
        --layout-fixed-right:,
        --layout-fixed-top: {
          position: fixed;
        }

`position:fixed` it not applied  when one of these rules is used. Presumably because it is not parsed out properly. Haven't tried, only reporting :)

https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout.html#L278-L283

**Comment by zmoshansky** [comment]
:+1: 

ex.) The following should be enough to align right, but it doesn't have the `position: fixed` attribute according to chrome inspector and as seen visually.
```
<style>
    paper-fab { @apply(--layout-fixed-right); }
</style>
...
<paper-fab icon="add"></paper-fab>
```

I'm not familiar with how to fix it ideally, but the repetitive, although technically more concise, method of adding `position: fixed` to all four items would work. Is that a suitable fix for a PR?

**Comment by notwaldorf** [comment]
@ebidel We don't think that's the syntax for apply the same style to multiple mixins, and it probably shouldn't work like that, but @sorvell should probably take a look at this and weigh in.

**Comment by notwaldorf** [comment]
I'm going to close this. That syntax is not really a thing, and it doesn't work in css either. Since it's _producing_ a value, it would be the equivalent of:
```css
.foo {
  display:,
  border:,
  text-shadow:
  none;
}
```
which is kind of bananas. 🍌
