### ISSUE TITLE
Chrome issue with style include attribute?

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/iron-flex-layout#82]
According to the documentation, it seems that include attributes can be applied to a "custom-style" element.
https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules

However, I have gotten rendering issues with Chrome when serving a gzipped, Vulcanized page that uses the following:
(Strangely, when opening the uncompressed, Vulcanized page locally, I do not have the same rendering issue.)
```html
<style is="custom-style" include="iron-flex iron-flex-alignment iron-flex-factors iron-positioning">
  :root{...styles...}
</style>
```

When I split the include attribute to its own empty tag, everything seems to render correctly:

```html
<style is="custom-style" include="iron-flex iron-flex-alignment iron-flex-factors iron-positioning">
</style>
<style is="custom-style">
  :root{...styles...}
<\style>
```

As an aside, I've tested Firefox, Edge, and IE11.  They all seem to render properly, regardless of the include attribute's location.

Is the include attribute not meant to work with a custom-style tag that has contents?

**Comment by notwaldorf** [comment]
Hmm, this shoooould be fine. @azakus any idea why vulcanize would care about this?

**Comment by azakus** [comment]
I'd need to see a more complete example. Perhaps an import for the styles to include is missing before the declaration and causing the styles to be ordered incorrectly.

**Comment by cpboyd** [comment]
The complete imports for that style.html file:
```html
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/iron-icons/iron-icons.html">
<link rel="import" href="bower_components/iron-icons/hardware-icons.html">
<link rel="import" href="bower_components/iron-flex-layout/iron-flex-layout.html">
<link rel="import" href="bower_components/iron-flex-layout/iron-flex-layout-classes.html">

<link rel="import" href="bower_components/paper-styles/color.html">
<link rel="import" href="bower_components/paper-styles/default-theme.html">
<link rel="import" href="bower_components/paper-styles/shadow.html">
<link rel="import" href="bower_components/paper-styles/typography.html">

<style is="custom-style" include="iron-flex iron-flex-alignment iron-flex-factors iron-positioning">
  :root {...styles...}
</style>
```

Honestly, I don't think it's an issue with Vulcanize (as the local Vulcanized HTML file loads the style correctly).

It's more likely some type of rendering quirk with Chrome, since the issue only happens when I'm serving the HTML from a device (with gzip encoding.)

I only opened this to confirm that I was understanding the documentation correctly, so I'll close this bug since it's not specifically Polymer related.
