### ISSUE TITLE
iron-flex-layout is deprecated but is used in other official components.

### ISSUE THREAD

**Issue by iSuslov** [PolymerElements/iron-flex-layout#92]
In console I see the message:

> This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead

I removed all imports for that dependency, but official polymer components still use this, for example:

> iron-image.html
> paper-item.html 

and others..

**Comment by notwaldorf** [comment]
Where do you see the `classes/iron-flex-layout.html` file being used in iron-image or paper-item? Neither of these elements, nor their demos use it

**Comment by notwaldorf** [comment]
(The warning comes from `iron-flex-layout/classes/iron-flex-layout.html`, not `iron-flex-layout/iron-flex-layout.html`. Could it be you're using old versions of these elements?)

**Comment by iSuslov** [comment]
Wow, thank you for such quick response. 
Maybe I installed old versions, but this is strange since I'm installing with bower.
Here is my `bower.json`:

> {
>   ....
>   "dependencies": {
>     "polymer": "Polymer/polymer#^1.4.0",
>     "iron-elements": "PolymerElements/iron-elements#^1.0.10",
>     "carbon-route": "PolymerElements/carbon-route#^0.8.4",
>     "gold-elements": "PolymerElements/gold-elements#^1.0.1",
>     "neon-elements": "PolymerElements/neon-elements#^1.0.0",
>     "google-map": "GoogleWebComponents/google-map#^1.1.10",
>     "paper-elements": "PolymerElements/paper-elements#^1.0.7"
>   }
> }
>

**Comment by notwaldorf** [comment]
Ah! The offending line is `<link rel="import" href="polymer/paper-styles/paper-styles.html">`. It includes the deprecated file [here](https://github.com/PolymerElements/paper-styles/blob/master/paper-styles.html#L12), which is why we recommend not using it (see [this note](https://github.com/PolymerElements/paper-styles/blob/master/paper-styles.html#L33).

**Comment by notwaldorf** [comment]
Closing, since this isn't an issue with this element :)

**Comment by iSuslov** [comment]
@notwaldorf Thank you Monica :)

**Comment by frank707** [comment]
I started seeing this warning in my console recently and noticed that iron-list component has a test / demo page that imports paper-styles.html.

https://github.com/PolymerElements/iron-list/blob/master/test/smoke/index.html

**Comment by notwaldorf** [comment]
@frank707 arg, i thought i had tracked down all of them. would you be interested in sending a PR to iron-list to fix that? /cc @blasten

**Comment by frank707** [comment]
Sure. Just sent a PR. :)

**Comment by amantri** [comment]
I am also seeing this warning, due to https://github.com/PolymerElements/app-layout/blob/master/app-toolbar/app-toolbar.html#L12 in my case

**Comment by alenkvakic** [comment]
@amantri i've got the same issue due to app-toolbar.html - did you find a solution to this warning with the element?

**Comment by amantri** [comment]
@alenkvakic, I did not find a solution. Since its only a warning, and doesn't appear to affect my app, I am ignoring it for now :)
